- name: Etcd kurulumu (Rocky Linux 9 Minimal)
  hosts: etcd
  become: true

  vars:
    etcd_version: "v3.5.14"
    etcd_download_url: "https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    etcd_install_dir: "/usr/local/bin"

  tasks:
    - name: Gerekli yardımcı paketleri kur
      yum:
        name:
          - tar
          - wget
          - curl
        state: present

    - name: etcd binary'yi indir
      get_url:
        url: "{{ etcd_download_url }}"
        dest: /tmp/etcd.tar.gz

    - name: etcd arşivini aç
      unarchive:
        src: /tmp/etcd.tar.gz
        dest: /tmp
        remote_src: yes

    - name: etcd ve etcdctl binary'lerini kopyala ve çalıştırılabilir yap
      copy:
        src: "/tmp/etcd-{{ etcd_version }}-linux-amd64/{{ item }}"
        dest: "{{ etcd_install_dir }}/{{ item }}"
        mode: '0755'
        remote_src: yes
      loop:
        - etcd
        - etcdctl

    - name: etcd config dosyasını oluştur
      template:
        src: templates/etcd.conf.j2
        dest: /etc/default/etcd
        mode: '0644'

    - name: etcd systemd servis dosyasını oluştur
      copy:
        dest: /etc/systemd/system/etcd.service
        content: |
          [Unit]
          Description=etcd key-value store
          Documentation=https://github.com/etcd-io/etcd
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/etcd
          Restart=always
          RestartSec=5
          LimitNOFILE=40000
          EnvironmentFile=-/etc/default/etcd

          [Install]
          WantedBy=multi-user.target

    - name: systemd daemon'ı yeniden yükle
      systemd:
        daemon_reload: yes

    - name: etcd servisini başlat ve etkinleştir
      systemd:
        name: etcd
        state: started
        enabled: yes

