- name: PostgreSQL & Patroni kurulumu (Rocky Linux 9 Minimal)
  hosts: postgres
  become: true

  vars:
    pg_version: "16"
    pg_bin_path: "/usr/pgsql-16/bin"

  tasks:
    - name: Gerekli sistem paketlerini kur
      yum:
        name:
          - epel-release
          - gcc
          - python3
          - python3-pip
          - python3-devel
          - libpq-devel
          - sudo
          - curl
        state: present

    - name: PostgreSQL PGDG .rpm dosyasını indir
      get_url:
        url: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        dest: /tmp/pgdg-redhat-repo-latest.noarch.rpm
    
    - name: PGDG GPG anahtarını indir
      get_url:
        url: https://download.postgresql.org/pub/repos/yum/keys/RPM-GPG-KEY-PGDG
        dest: /tmp/RPM-GPG-KEY-PGDG
        mode: '0644'
    
    - name: GPG anahtarını sisteme import et
      command: rpm --import /tmp/RPM-GPG-KEY-PGDG
      args:
        creates: /etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG
 
    - name: PGDG .rpm dosyasını yum ile kur
      yum:
        name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
        state: present


    - name: AppStream üzerinden gelen eski PostgreSQL'i devre dışı bırak
      shell: dnf -qy module disable postgresql

    - name: PostgreSQL paketlerini kur (PGDG'den)
      yum:
        name:
          - postgresql{{ pg_version }}
          - postgresql{{ pg_version }}-server
          - postgresql{{ pg_version }}-contrib
        state: present

    - name: Python virtualenv oluştur
      command: python3 -m venv /opt/patroni-venv
      args:
        creates: /opt/patroni-venv

    - name: Patroni ve bağımlılıkları kur
      pip:
        virtualenv: /opt/patroni-venv
        name:
          - patroni
          - psycopg2-binary
          - python-etcd

    - name: Patroni config dosyasını oluştur
      template:
        src: templates/patroni.yml.j2
        dest: /etc/patroni.yml
        mode: '0644'

    - name: Patroni systemd servis dosyasını kopyala
      template:
        src: templates/patroni.service.j2
        dest: /etc/systemd/system/patroni.service
        mode: '0644'

    - name: systemd servisini reload et ve Patroni'yi başlat
      systemd:
        name: patroni
        daemon_reload: yes
        enabled: yes
        state: started

